prompt = {
    "joy" : "Create a cheerful and energetic character inspired by the style of Joy from the movie 'Inside Out'. The character should have yellow hair that bounces as they move, reflecting their playful and optimistic personality. Their face should be highly expressive with large, sparkling eyes full of joy, and a wide, radiant smile that lights up their entire face. The character's emotions should be exaggerated, with every movement and facial expression radiating pure excitement and happiness. The background should use light, pastel tones to emphasize the character's bright and optimistic nature. , yellow hair ,yellow",
    "sadness" : "Create a character inspired by the style of Sadness from 'Inside Out'. The character should have dark blue hair, neatly cut, reflecting their calm yet melancholic personality. Their face should show deep sorrow, with tear-filled, droopy eyes and a subtle, quivering frown. Every aspect of their facial expression and body language should be exaggerated to convey overwhelming sadness and reluctance. The background should be simple and muted, possibly with mist or soft gradients, to highlight the character's heavy, melancholic mood. blue hair, blue",
    "anger" :"Create a character inspired by Anger from 'Inside Out'. The character should have short, fiery red hair, emphasizing their explosive temper. Their face should be contorted in pure rage, with furrowed eyebrows, a clenched jaw, and their mouth wide open in a furious scream. Every detail of their posture and facial expression should exaggerate their fury, as if they are about to explode. Flames or heated elements could be incorporated around the head or body, and the background should feature fiery colors like reds, oranges, and yellows to heighten the intensity of their anger. red hair, red",
    # "disgust"  : "Create a character inspired by Disgust from 'Inside Out'. The character should have sleek, well-groomed green hair that reflects their fashionable yet dismissive personality. Their face should show extreme distaste, with a wrinkled nose, raised eyebrow, and pursed lips. Their posture should be exaggerated, showing their disdain with an upright, elegant stance and a slightly turned-away face. The background can feature clashing colors or patterns to emphasize the character’s strong disapproval of their surroundings. , green hair, green, wearing glasses",
    # "serious" : "Create a character in the style of a Joseon-era scholar, with black hair neatly tied in a traditional topknot, wearing a white hanbok as the main color along with a traditional black gat (a Korean hat). The gat should be prominently featured, with its wide, flat brim and transparent mesh-like material, symbolizing the character’s scholarly status. The character’s face should reflect intense seriousness and critical thought, with sharp, narrowed eyes and a slightly furrowed brow. Their posture should be upright, with exaggerated gestures and movements that show their deep contemplation or strong critiques. The background could be a traditional Korean study room or a natural setting, enhancing the character's philosophical and critical nature. black hair ,black, wearing gat , black gat"
}



